# Generated by Django 5.1.2 on 2024-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="fist_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
