# Generated by Django 5.1.2 on 2024-10-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0003_profile_email_profile_fist_name_profile_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="fist_name",
            new_name="first_name",
        ),
    ]
