# Generated by Django 5.1.2 on 2024-11-03 08:27

import django.db.models.deletion
import shopapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_productimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, null=True, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", to="shopapp.product", verbose_name="товары"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.CharField(blank=True, max_length=20, verbose_name="промокод"),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.FileField(
                null=True, upload_to="orders/receipts/", verbose_name="рецепт"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="архивировано"),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(verbose_name="количество"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="создал",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(default=0, verbose_name="скидка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="превью",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="цена"
            ),
        ),
    ]
